# will use flask_social_media_backend as reference to create my flask backend..
# copy content and paste it, once I am confident enough, try to do some routes/models on my own..
# created two separate blueprints, one for authentication/user db, the other for the user's ability to create a portfolio....