"""added user cash attr

Revision ID: e959fad87045
Revises: edda967432d4
Create Date: 2022-09-13 20:33:43.413834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e959fad87045'
down_revision = 'edda967432d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cash', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cash')
    # ### end Alembic commands ###
